Project/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),

    path("", include("main.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/main/urls.py
from django.urls import path

import main.views as views

app_name = "main"

urlpatterns = [
    path("", views.AboutPage.as_view(), name="about"),
    path("map/", views.MapPage, name="map"),
    path("factory/<int:factory_id>/", views.FactoryPage.as_view(), name="factory"),
    path("article/<int:article_id>/", views.ArticlePage.as_view(), name="article"),
]

Project/main/models.py
from django.db import models
from django.urls import reverse


class Factory(models.Model):
    name = models.CharField(verbose_name="Название", max_length=100)
    description = models.TextField(verbose_name="Описание")
    lat_coord = models.DecimalField(max_digits=10, decimal_places=6, default=0.0)
    long_coord = models.DecimalField(max_digits=10, decimal_places=6, default=0.0)
    image = models.ImageField("Картинка завода", upload_to="factory_images/%Y/%m", null=True)
    is_factory = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Завод"
        verbose_name_plural = "Заводы"

    def get_absolute_url(self):
        return reverse('main:factory', kwargs={'factory_id': self.pk})


class Picture(models.Model):
    image = models.ImageField("Картинка", upload_to="images/%Y/%m")
    text = models.CharField("Подпись", max_length=100, null=True, blank=True)
    factory = models.ForeignKey(
        Factory, verbose_name="Фабрика", on_delete=models.CASCADE,
    )

    class Meta:
        default_related_name = "pictures"


class Article(models.Model):
    title = models.CharField(verbose_name="Заголовок", max_length=100)
    text = models.TextField(verbose_name="Текст")
    next = models.ForeignKey(
        "self", verbose_name="Следующая статья", on_delete=models.SET_NULL,
        null=True, blank=True
    )

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:article', kwargs={'article_id': self.pk})

Project/main/views.py
from django.views.generic import TemplateView, DetailView
from django.shortcuts import render

from main.models import Factory, Article

class AboutPage(TemplateView):
    template_name = "main/about.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["article"] = Article.objects.first()
        return context


class FactoryPage(DetailView):
    template_name = "main/factory.html"
    queryset = Factory.objects.all()
    context_object_name = "factory"
    pk_url_kwarg = 'factory_id'


def MapPage(request):
    factories = Factory.objects.all()

    return render(request, "main/map.html", {"factories": factories, "redirectTo": "/factory/"})


class ArticlePage(DetailView):
    template_name = "main/article.html"
    queryset = Article.objects.all()
    context_object_name = "article"
    pk_url_kwarg = 'article_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["prev"] = Article.objects.filter(next=self.get_object()).first()
        return context

Project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  <title>
      {% block title %}Страница{% endblock title %}
  </title>

  <link rel="stylesheet" href="{% static 'css/base.css' %}">

  {% block extra_head %}
  {% endblock extra_head %}
</head>

<body class="main-block">
  <header class="sticky-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="nav navbar-nav nav-pills ms-auto me-auto fs-5">
            <li class="nav-item">
              <h5><a class="nav-link px-2" href="{% url "main:about" %}">О проекте</a></h5>
            </li>
            <li class="nav-item">
              <h5><a class="nav-link px-2" href="{% url "main:map" %}">Карта</a></h5>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main>
  {% block content %}

  {% endblock content %}
  </main>
</body>

</html>

Project/templates/main/about.html
{% extends "base.html" %}

{% block title %}О проекте{% endblock title %}

{% block content %}
<div class="container">
    <h2 class="text-center fw-bold my-4">
        Добро пожаловать в виртуальный музей промышленности Урала XVIII века!
    </h2>
    <p class="fs-5">Пройдясь по залам нашего музея, вы познакомитесь с династиями промышленников, узнаете, как работали уральские заводы и что они производили.</p>

    <div class="text-center m-5">
        <a class="btn btn-primary btn-lg fs-5" href="{{ article.get_absolute_url }}">Начать осмотр</a>
    </div>

    <p class="fs-5">Также в нашем музее вы можете познакомиться с историей наиболее известных металлургических предприятий Урала. Для этого перейдите в раздел <a class="text-decoration-none" href="{% url "main:map" %}">Карта</a> и кликните на заинтересовавший вас завод.</p>
    
    <div class="text-center m-5">
        <a class="btn btn-success btn-lg fs-5" href="{% url "main:map" %}">Перейти к карте</a>
    </div>
</div>

<div class="border-top container" style="margin-top: 14%;">
    <h5>Список использованной литературы:</h5>
    <ul>
        <li>Хью Хадсон-мл. Первые Демидовы и развитие чёрной металлургии России в XVIII веке;</li>
        <li>Лотарёва Р. М. Города-заводы России : XVIII — первая половина XIX века;</li>
        <li>Гудков Г. Ф., Гудкова З. И. Из истории южноуральских горных заводов XVIII—XIX веков : Историко-краеведческие очерки.</li>
    </ul>
    <h5>Сайт сделан студентами группы 232 ОП Программная инженерия ФКН НИУ ВШЭ:</h5>
    <p>Мякишев Артемий, Косов Филимон, Сайгитов Гаджимурад, Маренков Алексей, Поляков Данила</p>
</div>
{% endblock content %}

Project/templates/main/article.html
{% extends "base.html" %}

{% block title %}{{ article.title }}{% endblock title %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-5">{{ article.title }}</h1>
    {{ article.text|safe }}

    <div class="my-5 d-flex justify-content-between">
        <div>
            {% if prev %}
            <a class="btn btn-success btn-lg" href="{{ prev.get_absolute_url }}">Предыдущий зал</a>
            {% endif %}
        </div>
        <div>
            {% if article.next %}
            <a class="btn btn-success btn-lg" href="{{ article.next.get_absolute_url }}">Следующий зал</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}
 

Project/templates/main/factory.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{ factory.name }}
{% endblock title %}

{% block extra_head %}
<link href="{% static "css/styles_factory.css" %}" rel="stylesheet" type="text/css"/>
{% endblock extra_head %}
 
 {% block content %}
<div class="my-block">
	
	<div class="header" style="background-image: url('{{ factory.image.url }}');">
		<div class="header-title">
			<div class="title bg-white mx-auto w-50 rounded-5 text-black">{{ factory.name }}</div>
		</div>
	</div>
	
	<div class="container-sm container-md container-lg container-xl container-xxl mb-5">
		<div class="text">
			<p>{{ factory.description|linebreaks }}</p>
		</div>
		<div class="gallery">
			<div class="title">Галерея</div>
			{% for picture in factory.pictures.all %}
				<img class="foto mw-100 h-auto" src="{{ picture.image.url }}" alt="фото">
				{% if picture.text %}
				<p class="fst-italic fs-6">{{ picture.text }}</p>
				{% endif %}
			{% endfor %}
		</div>
	</div>

</div>

{% endblock content %}

Project/templates/main/map.html
{% extends "base.html" %}
{% load l10n %}

{% block title %}Карта{% endblock title %}

{% block extra_head %}

<meta http-equiv="content-type" content="text/html; charset=UTF-8" />

    <script>
        L_NO_TOUCH = false;
        L_DISABLE_3D = false;
    </script>

<style>html, body {width: 100%;height: 100%;margin: 0;padding: 0;}</style>
<style>#map {position:absolute;top:200px;bottom:0;right:0;left:0;}</style>
<script src="https://cdn.jsdelivr.net/npm/leaflet@1.9.3/dist/leaflet.js"></script>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.9.3/dist/leaflet.css"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.0/css/all.min.css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/python-visualization/folium/folium/templates/leaflet.awesome.rotate.min.css"/>

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<style>
    #map {
        position: static;
        width: 99.9%;
        height: 93vh;
        top: 0px;
    }
    .leaflet-container { font-size: 1rem; }
</style>

<script src="https://cdn.jsdelivr.net/npm/leaflet.fullscreen@3.0.0/Control.FullScreen.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet.fullscreen@3.0.0/Control.FullScreen.css"/>

{% endblock extra_head %}

{% block content %}

<div>
<div class="folium-map" id="map" ></div>
</div>

<script>
        var map = L.map(
            "map",
            {
                center: [55.661563, 57.425278],
                crs: L.CRS.EPSG3857,
                zoom: 6,
                zoomControl: true,
                preferCanvas: false,
            }
        );

        var tile_layer = L.tileLayer(
            "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
            {"attribution": "Data by \u0026copy; \u003ca target=\"_blank\" href=\"http://openstreetmap.org\"\u003eOpenStreetMap\u003c/a\u003e, under \u003ca target=\"_blank\" href=\"http://www.openstreetmap.org/copyright\"\u003eODbL\u003c/a\u003e.", "detectRetina": false, "maxNativeZoom": 18, "maxZoom": 18, "minZoom": 0, "noWrap": false, "opacity": 1, "subdomains": "abc", "tms": false}
        );

        tile_layer.addTo(map);

        var factory_icon = L.icon({"iconUrl": "https://cdn-icons-png.flaticon.com/512/5131/5131491.png"});
        var town_icon = L.icon({"iconUrl": "https://cdn-icons-png.flaticon.com/512/3002/3002597.png"});
        {% for factory in factories %}
            {% localize on %}

            var marker = L.marker(
                         [{{ factory.lat_coord|unlocalize }}, {{ factory.long_coord|unlocalize }}],
                         {}
                         ).addTo(map).on('click', function() {
                            window.location.href = '{{ redirectTo }}' + '{{ factory.id }}';
                         });;

            {% endlocalize %}

            marker.bindTooltip(
                `
                 <figure>
                 <img style="max-width:700px;max-height:700px;" src="/media/{{ factory.image }}">
                 <figcaption style="text-align: center;"> {{ factory.name }} </figcaption>
                 </figure>
                 `,
                {"sticky": true}
            );

            {% if factory.is_factory == True %}
                marker.setIcon(factory_icon);
            {% else %}
                marker.setIcon(town_icon);
            {% endif %}

        {% endfor %}

        L.control.fullscreen(
            {"forceSeparateButton": true, "position": "topright", "title": "Expand", "titleCancel": "Exit"}
        ).addTo(map);

</script>


{% endblock content %}